config/routes.rb
Techblog::Application.routes.draw do

  resources :settings

  resources :admin, :controller => :admins
  resources :admins

  resources :posts

  root 'posts#index'
  get "/posts/tag/:tag" => "posts#tag"
  get "/posts/*sub_id" => "posts#show"

  post "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  get "/tags/:tag" => "posts#tag"

  get '*path', :controller => "posts", :action => "route_not_found"

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h2>Admins</h2>

<table class="table">
  <thead>
    <tr>
      <th>email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <% if @admins.length > 1 %>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>


<h2>Settings</h2>

<%= render 'settings/form' %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', '/admin' %>