config/routes.rb
Techblog::Application.routes.draw do

  resources :settings

  resources :admin, :controller => :admins
  resources :admins

  resources :posts

  root 'posts#index'
  get "/posts/tag/:tag" => "posts#tag"
  get "/posts/*sub_id" => "posts#show"

  post "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  get "/tags/:tag" => "posts#tag"

  get '*path', :controller => "posts", :action => "route_not_found"

end

app/models/setting.rb
class Setting
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :description, type: String
  field :about, type: String
  field :language, type: String
  field :ga_tracking_code, type: String
  field :github_id, type: String
  field :twitter_id, type: String
  field :facebook_url, type: String

  def self.get_data
    data = self.first
    unless data
      data = self.create({
        :title            => "TechBlog",
        :description      => "",
        :language         => "ja",
        :ga_tracking_code => "",
        :github_id        => "",
        :twitter_id       => "",
        :facebook_url     => ""
      })
    end
    data
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    #redirect_to :controller => 'admins', :action => 'index'
    #redirect_to '/admins'

    respond_to do |format|
      if @setting.set(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(
        :title,
        :description,
        :about,
        :language,
        :ga_tracking_code,
        :github_id,
        :twitter_id,
        :facebook_url
      )
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for @setting, :html => {'role' => "form"} do |f| %>

  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :about %><br>
    <%= f.text_area :about, :size => "100x5", :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :language %><br>
    <%= f.text_field :language, :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :google_analytics_tracking_code %><br>
    <%= f.text_area :ga_tracking_code, :size => "100x15", :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label "github id" %><br>
    <%= f.text_field :github_id, :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label "twitter id" %><br>
    <%= f.text_field :twitter_id, :class => "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label "facebook url" %><br>
    <%= f.text_field :facebook_url, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Language</th>
      <th>Google analytics account</th>
      <th>Github</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.title %></td>
        <td><%= setting.description %></td>
        <td><%= setting.language %></td>
        <td><%= setting.ga_tracking_code %></td>
        <td><%= setting.github_id %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @setting.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @setting.description %>
</p>

<p>
  <strong>Language:</strong>
  <%= @setting.language %>
</p>

<p>
  <strong>Google analytics account:</strong>
  <%= @setting.ga_tracking_code %>
</p>

<p>
  <strong>Github:</strong>
  <%= @setting.github_id %>
</p>

<%= link_to 'Back', '/admin' %>