config/routes.rb
Techblog::Application.routes.draw do

  resources :settings

  resources :admin, :controller => :admins
  resources :admins

  resources :posts

  root 'posts#index'
  get "/posts/tag/:tag" => "posts#tag"
  get "/posts/*sub_id" => "posts#show"

  post "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  get "/tags/:tag" => "posts#tag"

  get '*path', :controller => "posts", :action => "route_not_found"

end

app/models/post.rb
require 'nokogiri'

class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Taggable
  paginates_per 10

  field :title, type: String
  field :body, type: String
  field :sub_id, type: String
  index({ sub_id: 1 }, { unique: true })

  def body_html(opts={})
    return nil unless body
    get_markdown.render(body)
  end

  def body_html_by_line_count(line_count)
    return nil unless body
    get_markdown.render(body.split("\n")[0..line_count].join("\n"))
  end

  def body_html_by_keywords(keywords)
    return nil unless body
    html = get_markdown.render(body)
    doc = Nokogiri::HTML.parse(html)
    doc.css('* :not(html) :not(body)').each do |node|
      keywords.each do |keyword|
        node.inner_html = node.inner_html.gsub(keyword, "<span class='keyword-match'>#{keyword}</span>")
      end
    end
    doc.css("body").to_html
  end

  def created_at_fmt
    created_at.strftime("%e %B %Y")
  end

  def default_sub_id
    time = created_at ? created_at : Time.now
    time.strftime("%Y/%m/%d/%H%M%S")
  end

  private
    def get_markdown
      render   = Redcarpet::Render::HTML.new(:prettify => true)
      markdown = Redcarpet::Markdown.new(render,
        :fenced_code_blocks => true,
        :tables => true,
        :autolink => true,
        :strikethrough => true
      )
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :set_post_by_sub_id, only: [:show_by_sub_id]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_tag_cloud, only: [:index, :tag, :show, :new, :edit]

  # GET /posts
  # GET /posts.json
  def index
    if params["keyword"]
      @keywords = params["keyword"].split(" ")
      @posts = find_by_keywords(@keywords)
    else
      @posts = Post.order('created_at DESC').page params[:page]
    end
    @is_index = true
  end

  def route_not_found
    flash[:error] = "Route not found"
    redirect_to action: 'index'
  end

  def tag
    @posts = Post.tagged_with(params['tag']).order('created_at DESC').page params[:page]
    render :template => "posts/index"
  end

  def set_tag_cloud
    @tag_cloud = Post.tags_with_weight[0..20]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    session[:recent_shows] ||= []
    post_hash = {:title => @post.title, :id => @post.id.to_s}

    unless session[:recent_shows].include?(post_hash)
      session[:recent_shows].push(post_hash)
    end

    if session[:recent_shows].length > 3
      # 末尾3つを残す
      length = session[:recent_shows].length
      session[:recent_shows] = session[:recent_shows][length-3..-1]
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.sub_id = @post.default_sub_id
    respond_to do |format|
      if @post.save
        # @post.tag(post_params[:tags], current_user) if post_params[:tags]
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: nil }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    # @post.delete_all_tags
    # @post.tag(post_params[:tags], current_user) if post_params[:tags]
    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    # @post.delete_all_tags
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      if params[:sub_id]
        @post = Post.find_by(sub_id: params[:sub_id])
      else
        @post = Post.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      if params["post"]["tags"].class == Array
        params["post"]["tags"] = params["post"]["tags"].join(',')
      end
      params.require(:post).permit(:sub_id, :title, :body, :tags, :created_at, :updated_at)
    end

    def create_and_conds(target, keywords)
      and_conds = []
      keywords.each do |keyword|
        and_conds << {target => /#{keyword}/i}
      end
      and_conds
    end

    def find_by_keywords(keywords)
      search_cond = {:$or => [
        {:$and => create_and_conds(:title, keywords)},
        {:$and => create_and_conds(:body,  keywords)}
      ]}
      posts = Post.where(search_cond)
      posts.order('created_at DESC').page(params[:page]).per(100)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group form-group field">
    <span class="input-group-addon">Title</span>
    <%= f.text_field :title, :class => "form-control", :placeholder => "Title" %>
  </div>

  <div class="form-group field" tabindex="1">
    <ul class="nav nav-tabs">
      <li class="active" id="btn_write"><a href="javaScript:void(0)" tabindex="1">Write</a></li>
      <!--<li id="btn_preview"><a href="javaScript:void(0)" tabindex="1">Preview</a></li>-->
    </ul>

    <%= f.text_area :body, :cols => "50", :rows => "15", :id => "post_body" %>
  </div>

  <div class="form-group input-group field">
    <span class="input-group-addon">Tags</span>
    <%= f.text_field :tags, :class => "form-control", :placeholder => "rails, ruby" %>
  </div>

  <div class="actions">
    <%= f.submit "Publish", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to post.title, post_path(post) %></h2>
  <p class="blog-post-meta"><%= post.created_at_fmt %></p>
  <div class="tweet share-link clearfix">
    <!-- TODO: set domain -->
    <a href="http://b.hatena.ne.jp/entry/www.kyamada.com/posts/<%= post.sub_id %>"
       class="hatena-bookmark-button"
       data-hatena-bookmark-title="<%= post.title %>"
       data-hatena-bookmark-layout="standard-balloon"
       data-hatena-bookmark-lang="en"
       title="このエントリーをはてなブックマークに追加">
      <img src="http://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a>

    <a href="https://twitter.com/share"
      class="twitter-share-button"
      data-url="http://www.kyamada.com/posts/<%= post.sub_id %>"
      data-text="<%= post.title %>"
      data-via="">Tweet</a> <!--TODO: set twitter user id to data-via -->
  </div>

  <div class="tags">
    <% post.tags_array.each do |tag| %>
      <a href='/posts/tag/<%= tag %>'><i class="fa fa-tag"></i> <%= tag %></a>
    <% end %>
  </div>

  <% if current_user %>
    <div style="text-align:right">
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

  <div class="body">
    <% if @keywords %>
      <%= post.body_html_by_keywords(@keywords).html_safe %>
    <% else %>
      <%= post.body_html.html_safe %>
    <% end %>
  </div>
</div><!-- /.blog-post -->

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>
<br>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<script type="text/javascript">
  $(function() {
    new Techblog.Views.Posts.EditView({post: <%= @post.to_json.html_safe -%>});
  });
</script>

app/views/posts/index.html.erb
<div id="posts">
  <% @posts.each do |post| %>
    <%= render "post", :post => post %>
  <% end %>
<hr/>

</div>

<script type="text/javascript">
  $(function() {
    // window.router = new Techblog.Routers.PostsRouter({posts: <%= @posts.to_json.html_safe -%>});
    //posts = <%= raw render :template => 'posts/index.json.jbuilder' %>;
    //window.router = new Techblog.Routers.PostsRouter({posts: posts});
    //Backbone.history.start();
    TB.Util.setStyle()
  });
</script>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="posts">
  <%= render "post", :post => @post %>
</div>

<script type="text/javascript">
  $(function() {
    TB.Util.setStyle()
  });
</script>

<div>
  <%= render "shared/ads_google_300_250" %>
</div>